name: Streamlit App Deployment

on:
  push:
    branches:
      - main  # change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Specify the Python version here

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming your dependencies are listed in requirements.txt

      - name: Download NLTK Data
        run: |
          python -m nltk.downloader punkt
          python -m nltk.downloader stopwords
          python -m nltk.downloader wordnet

      - name: Run Streamlit App
        run: |
          streamlit run streamlit_app.py  # Command to run your Streamlit app