[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"
